Repository ASFHyP3/hyp3-srg, pull requests merged in 2024-04, with the labels that each got.

#14 Release v0.2.0
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/dependabot.yml
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  Dockerfile
  LICENSE
  MANIFEST.in
  README.md
  back_projection/__init__.py
  back_projection/__main__.py
  back_projection/process.py
  environment.yml
  pyproject.toml
  setup.py
  src/hyp3_back_projection/__init__.py
  src/hyp3_back_projection/__main__.py
  src/hyp3_back_projection/etc/entrypoint.sh
  src/hyp3_back_projection/process.py
  tests/conftest.py
  tests/test_entrypoints.py
Labels: minor

#15 Update PAK name in workflows
  .github/workflows/release.yml
  .github/workflows/tag-version.yml
Labels: bumpless

#16 GitHub Actions stuff
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
Labels: bumpless

#19 Use FFTW3 from Package Manager
  CHANGELOG.md
  Dockerfile
  scripts/build_proc_cpu.sh
Labels: enhancement, patch
